#-------------------------------------------------------------------------#
#                                                                         #
#                 FUNCTIONS TO CONTROL MACAULAY2 SOFTWARE                 #
#                                                                         #
#-------------------------------------------------------------------------#

# V1 FECHA

#-------------------------------------------------------------------------#
# OBSERVACIONES:

# 1. Bla bla bla
# 2. Bla bla bla
# 3. Bla bla bla
#


# soatnuh -----------------------------------------------------------------



#-------------------------------------------------------------------------#




#' Generator of a Macaulay2 file
#'
#'
#'
#' @param text_to_run vector with the commands of the Macaulay2 software that will be write in the file
#' @param add_date bolean that controls if the date of generation of the file should be printed on the .m2 file
#' @param folder_M2_files folder where the file will be store
#' @param M2_file_name name of the Macaulay2 file (the name of the .m2 file)
#'
#' @return
#' @export
#'
#' @examples
#' 
#' initial_comments <- c("This is a .m2 file generated by the function gen_m2_file","Author: Arrigo Coen") # beginning comments
#' text_to_run <- c("R = QQ[x,y,z]","I = ideal(x-2*y+3*z-7,2*x+y+z-4,-3*x+2*y-2*z+10)","primaryDecomposition I") # the equation to run
#' M2_file_name <- "Macaulay2_file" # the folder were the .m2 files will be stored
#' output_folder_m2_files <- "Macaulay2_output" # the folder were the output files of the .m2 files will be save
#' folder_M2_files<- "Macaulay2_files" # name of the .m2 file that we generate
#' output_file_name = "Solving_equation_with_Macaulay2_OUT" # name of output txt file
#' add_date = F
#' add_date = T
gen_m2_file <- function(text_to_run,M2_file_name,folder_M2_files, add_date=T) {
  # Correcting initial comments
  if(add_date) initial_comments <- c(initial_comments, paste("Generated on",format(Sys.time(), "%b %d %Y, at %X")))
  initial_comments <- paste0(c("-- ",paste0(initial_comments,collapse = "\n-- ")),collapse = "")
  # Correcting text
  text_to_run <- paste0(text_to_run,"\n")
  # Adding comments and text to run
  text_to_run <- paste0(c(initial_comments,"\n\n",text_to_run,"\n"))
  # File path
  file_name <- paste0(c(folder_M2_files,"/",M2_file_name,".m2"),collapse = "")
  # Writing the .m2 file
  write.table(text_to_run, file=file_name, append = F, sep = "", dec = ".",row.names = F, col.names = F, quote = FALSE)
  cat("The file ",file_name," was generated\n")
}


#' Generate text of the M2 file
#'
#' @param vec_variables 
#' @param vec_equations 
#'
#' @return
#' @export
#'
#' @examples
#' 
#' initial_comments <- c("This is a .m2 file generated by the function gen_m2_file","Author: Arrigo Coen") # beginning comments
#' M2_file_name <- "Macaulay2_file" # the folder were the .m2 files will be stored
#' output_folder_m2_files <- "Macaulay2_output" # the folder were the output files of the .m2 files will be save
#' folder_M2_files<- "Macaulay2_files" # name of the .m2 file that we generate
#' output_file_name = "Solving_equation_with_Macaulay2_OUT" # name of output txt file
#' add_date = F
#' add_date = T
#' vec_equations = c("x-2*y+3*z-7","2*x+y+z-4","-3*x+2*y-2*z+10")
#' vec_variables = c("x","y","z")
#' gen_eq_solver_text_for_m2_files(vec_variables, vec_equations) 
#' 
gen_eq_solver_text_for_m2_files <- function(vec_variables, vec_equations) {
  
  text_R = paste0("R = QQ[",paste0(vec_variables,collapse = ","),"]")
  text_I = paste0("I = ideal(",paste0(vec_equations,collapse = ", "),")")
  text_primaryI = "primaryDecomposition I"
  
  text_to_run = c(text_R, text_I,text_primaryI)
  return(text_to_run)
}