#-------------------------------------------------------------------------#
#                                                                         #
#                           NOMBRE DE ARCHIVO                             #
#                                                                         #
#-------------------------------------------------------------------------#

# V1 FECHA

#-------------------------------------------------------------------------#
# OBSERVACIONES:

# 1. Bla bla bla
# 2. Bla bla bla
# 3. Bla bla bla
#
#-------------------------------------------------------------------------#


# Packages ----------------------------------------------------------------


library(openxlsx)

library(readtext)
#install.packages("")

# Carpeta del proyecto ----------------------------------------------------

cat("\014") # borra consola 
rm(list=ls())  # Borra todo

# 1. Home
# 2. Work
# 3. Laptop
# 4. Other
rutas_prueba <- c("/Users/arrigocoen/Dropbox","/Users/useradmin/Dropbox","","")
eleccion_compu <- which(file.exists(rutas_prueba))

# Direcciones de cada computadora
source_raiz <- c("",# 1. Home
                 "",# 2. Work
                 "",# 3. Laptop
                 "")[eleccion_compu]# 4. Other

setwd(source_raiz)

# source("")
# library()


# CODE --------------------------------------------------------------------

cat("\014") # borra consola 
rm(list=ls())  # Borra todo
# source("Fn phylo R.R")
source("/Users/arrigocoen/Dropbox/1 Phylogenetics/2019/Ransanec/R/Fn phylo R.R")

Z0_t1 <- 0

K <- 3
K <- 8
K <- 4


l_var <- Gen_eq_mat_text(K,Z0_t1) 

l_var$mat_eq_text
dim(l_var$mat_eq_text)

names(l_var)
colnames(l_var$mat_eq_text)

# Function ----------------------------------------------------------------



# Generating M2 files -----------------------------------------------------


cat("\014") # borra consola 
rm(list=ls())  # Borra todo
source("Functions.R")

initial_comments <- c("This is a .m2 file generated by the function gen_m2_file","Author: Arrigo Coen") # beginning comments
text_to_run <- c("R = QQ[x,y,z]","I = ideal(x-2*y+3*z-7,2*x+y+z-4,-3*x+2*y-2*z+10)","primaryDecomposition I") # the equation to run
M2_file_name <- "Macaulay2_file" # the folder were the .m2 files will be stored
output_folder_m2_files <- "Macaulay2_output" # the folder were the output files of the .m2 files will be save
folder_M2_files<- "Macaulay2_files" # name of the .m2 file that we generate
output_file_name = "Solving_equation_with_Macaulay2_OUT" # name of output txt file
add_date = F
add_date = T

gen_m2_file(text_to_run,M2_file_name,folder_M2_files, add_date=T) 



# Example of function gen_eq_solver_text_for_m2_files ---------------------

cat("\014") # borra consola 
rm(list=ls())  # Borra todo
source("Functions.R")

initial_comments <- c("This is a .m2 file generated by the function gen_m2_file","Author: Arrigo Coen") # beginning comments
M2_file_name <- "Macaulay2_file" # the folder were the .m2 files will be stored
output_folder_m2_files <- "Macaulay2_output" # the folder were the output files of the .m2 files will be save
folder_M2_files<- "Macaulay2_files" # name of the .m2 file that we generate
output_file_name = "Solving_equation_with_Macaulay2_OUT" # name of output txt file
add_date = F
add_date = T
vec_equations = c("x-2*y+3*z-7","2*x+y+z-4","-3*x+2*y-2*z+10")
vec_variables = c("x","y","z")

gen_eq_solver_text_for_m2_files(vec_variables, vec_equations) 

gen_m2_file(text_to_run,M2_file_name,folder_M2_files, add_date=T)


# Running Macaulay2 using R -----------------------------------------------


cat("\014") # borra consola 
rm(list=ls())  # Borra todo
source("Functions.R")

# run_M2_Terminal_using_R(input_file_name,output_file_name,input_folder_m2_files,output_folder_m2_files)


initial_comments <- c("This is a .m2 file generated by the function gen_m2_file","Author: Arrigo Coen") # beginning comments
M2_file_name <- "Macaulay2_file" # the folder were the .m2 files will be stored
folder_M2_files<- "Macaulay2_files" # name of the .m2 file that we generate
folder_M2_files<- "/Users/arrigocoen/Dropbox/GitHub/2020 Arrigo Repos/How_to_use_Macaulay2_with_R/Macaulay2_files" # name of the .m2 file that we generate
folder_output_M2_files <- "Macaulay2_output" # the folder were the output files of the .m2 files will be save
folder_output_M2_files <- "/Users/arrigocoen/Dropbox/GitHub/2020 Arrigo Repos/How_to_use_Macaulay2_with_R/Macaulay2_output" # the folder were the output files of the .m2 files will be save
output_file_name = "Macaulay2_file_OUT" # name of output txt file

M2_file <- paste0(c(folder_M2_files,"/",M2_file_name,".m2"),collapse = "")
M2_file_out <- paste0(c(folder_output_M2_files,"/",output_file_name,".txt"),collapse = "")

file.exists(M2_file)
M2_file


# cat Macaulay2_input/Solving_equation_with_Macaulay2.m2 | M2 &> Macaulay2_output/Solving_equation_with_Macaulay2_out.txt



terminal_command <- 'cd "/Users/arrigocoen/Dropbox/GitHub/2020 Arrigo Repos/How_to_use_Macaulay2_with_R"'
system(terminal_command)

file_and_path <- paste0(c(folder_M2_files,"/",M2_file_name,".m2"),collapse = "")
terminal_command <- paste0(c('cat "',file_and_path,'" | M2 &> "',M2_file_out,'"'),collapse = "")

system(terminal_command)

terminal_command

# aouhea ------------------------------------------------------------------


terminal_command <- 'cd "/Users/arrigocoen/Dropbox/GitHub/2020 Arrigo Repos/How_to_use_Macaulay2_with_R"'
system(terminal_command)


# aneuht ------------------------------------------------------------------


# Using a test folder -----------------------------------------------------




# Running M2 files --------------------------------------------------------


# From M2 output to LaTeX -------------------------------------------------











# asotueh -----------------------------------------------------------------







