-- This is a .m2 file generated by the function gen_m2_file
-- Author: Arrigo Coen
-- Generated on Nov 02 2020, at 19:47:43



R = QQ[x,y,z]

I = ideal(x-2*y+3*z-7, 2*x+y+z-4, -3*x+2*y-2*z+10)

primaryDecomposition I



